AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an IAM role with permissions that can be assumed by a specified role in the Hub account.

Parameters:
  ProjectName:
    Type: String
    Description: This value will be used in the naming of the resources. This value should be the same as the Hub stack [ProjectName] parameter.
    Default: ec2demo

  CodeBuildRoleArn:
    Type: String
    Description: The ARN of the CodePipeline role that should be allowed to assume the Terraform Spoke Role for cross-account access.

Resources:
  TerraformSpokeRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${ProjectName}-terraform-spoke-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref CodeBuildRoleArn
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'
      Path: "/"
      Description: "Cross account (Spoke) role to be assumed by a principal for Terraform purposes."

Outputs:
  TerraformSpokeRoleARN:
    Description: The ARN of the Spoke Role
    Value: !GetAtt TerraformSpokeRole.Arn
  TerraformSpokeRoleName:
    Description: The ARN of the Spoke Role
    Value: !Ref TerraformSpokeRole